language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
  - go: tip

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

script:
- make build
- make test
- echo '+-----------------+@|1     7       9  |@|        1       6|@|8         6   7  |@|9   3   8   1    |@|                 |@|    8   2   5   7|@|  4   6         5|@|3       5        |@|  2       4     8|@+-----------------+' | tr @ "\n" | ./sudoku -
- make cover
- goveralls -service=travis-ci -v -covermode=count -coverprofile=profile.out
